import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Wrapper, Banner } from '../styles/index_style';

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Today Styling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Banner>
          여긴배너
        </Banner>
        <Wrapper>
        </Wrapper>
      </Container>
    </>
  )
}

export default Home
